### ISSUE TITLE
Gracefully handle JSON

### ISSUE THREAD

**Issue by tilacog** [graphprotocol/block-oracle#120]
Currently, if a single JSON RPC request fails for a single provider, the whole latest block polling operation fails, even if all the rest succeded.

We should refactor the [`get_latest_blocks`](https://github.com/graphprotocol/block-oracle/blob/3f2fe0df18ef8a7a2eae214efc13af753880b154/crates/oracle/src/jrpc_utils.rs#L101) function to gracefully handle partially failed polling attempts.

**Comment by neysofu** [comment]
Closed by #147.
