### ISSUE TITLE
Move Data Edge contract to `graphprotocol/contracts`

### ISSUE THREAD

**Issue by neysofu** [graphprotocol/block-oracle#156]
We should consider moving the Data Edge contract's source code over to https://github.com/graphprotocol/contracts/, where all protocol contracts are.

@abarmat WDYT?

**Comment by abarmat** [comment]
@neysofu @tmigone we may move it, but not sure as the Data Edge is a quite general contract that people can use for multiple use cases, it's not related or read from any of the other contracts in the protocol.

**Comment by tmigone** [comment]
think you meant to tag @tilacog 😵‍💫

**Comment by neysofu** [comment]
@abarmat makes sense, I had that thought but I wanted to get your opinion. Seems like we should just keep it here, then. Thanks :) 

Closing.
