### ISSUE TITLE
Reuse `oracle-encoder` logic in `xtask send-message`

### ISSUE THREAD

**Issue by tilacog** [graphprotocol/block-oracle#157]
This `enum` is effectively duplicating a subset of the `oracle-encoder` logic. We can get more features with less code if we simply ask the user for a `.json` file and compile that into a payload on the fly using `oracle-encoder` as a library:

`$ cargo xtask send-message ../config/dev/config.toml reset-message.json`

_Originally posted by @neysofu in https://github.com/graphprotocol/block-oracle/pull/135#discussion_r929825812_

**Comment by neysofu** [comment]
@tilacog we might have a easier time telling council people to run `block-oracle generate ...` rather than using `cargo`, which they might not even have installed. So I'd say this issue has a new-found priority with the recent decision regarding `RegisterNetwork`. WDYT?
