### ISSUE TITLE
Implement end-to-end verifiability of Oracle's messages

### ISSUE THREAD

**Issue by tilacog** [graphprotocol/block-oracle#197]
Since the Council is responsible for reviewing the proposed `RegesterNetworks` messages, it is necessary that reviewers can understand the encoded payloads they are signing.

Thus, this crate should provide `decode` command that can parse any given payload into a human-friendly representation of the `Message` sent to the Data Edge contract.

For instance, this input:
```txt
0x0305015505156569703135353a313030156569703a3135353a3737
```

Is expected to produce this output:
```json
[
  {
    "message": "RegisterNetworks",
    "add": [
        "eip155:100",
        "eip:155:77"
    ],
      "remove": [0, 42]
  }
]

```

We could host a static web app that encodes/decodes any given input for maximum usability.

cc: @abarmat

**Comment by tilacog** [comment]
Maybe there is a way to extract that functionality from the Epoch Subgraph code so we don't have to rewrite it in Rust?

**Comment by neysofu** [comment]
End-to-end verifiability is possible even without a decoder, because the encoding process is fully deterministic. We can provide a JSON specification and council members can independently verify that it compiles as it should. Am I missing something, @tilacog ?

**Comment by tilacog** [comment]
I agree that the current code already addresses the verifiability issue.

However, I think this is more of a user experience issue. Perhaps not all Council members (reviewers) are expected to be familiar with the command line.

In my last conversation with @abarmat, we thought that a web page with a simple decoding form would be the most convenient interface for the board to review the payload contents, but we can delve deeper it this and come up with the ideal requirements for this task.

cc: @azf20

**Comment by tilacog** [comment]
Some alternatives that @neysofu and I discussed:
1. Export the JSON encoding functionality to WASM and host it with Github pages, or
2. Provide a `POST /encoding` endpoint in the EBO container that accepts the JSON message and returns the payoad. We could then expose this in one of our domains.
