### ISSUE TITLE
Implement Transaction Monitoring

### ISSUE THREAD

**Issue by tilacog** [graphprotocol/block-oracle#215]
Currently, the Epoch Block Oracle optimistically halts until DataEdge transactions ar included in a block. 

If gas prices increase, the program will wait forever as it does not attempt any retries with adjusted gas prices.

We already have the [plans](https://github.com/graphprotocol/block-oracle/blob/main/crates/oracle/docs/transaction-monitoring.org) for the transaction monitoring feature.

**Comment by neysofu** [comment]
Closed by #219
