### ISSUE TITLE
[BUG]: [GLOBAL]: EPOCH ORACLE ISSUE - returns same gnosis block for any epoch

### ISSUE THREAD

**Issue by davaymne** [graphprotocol/block-oracle#221]
Please review the original issue: https://github.com/graphprotocol/indexer/issues/538

Scope: GLOBAL.
Impact: indexer keeps closing allocations per every given subgraph with the same POI acrross all epochs
Root Cause: EPOCH ORACLE ISSUE - returns same gnosis block for any requested epoch

Background:
Indexers closing a particular allocation during the same epoch should submit their proof of indexing at the start block number of the epoch. Epoch Oracle returns same gnosis block for any epoch requested by Agent, hence Agent submits same POI for every closed allocation per given subgraph.

**Comment by neysofu** [comment]
Thanks for the report @davaymne! We experienced JSON-RPC provider unavailability and our alert system failed to fire, apologies. It's fixed now.

```json
{
  "data": {
    "network": {
      "latestValidBlockNumber": {
        "network": {
          "id": "eip155:100"
        },
        "epochNumber": "1261",
        "blockNumber": "24916342",
        "previousBlockNumber": {
          "network": {
            "id": "eip155:100"
          },
          "epochNumber": "1260",
          "blockNumber": "24758015"
        }
      }
    }
  }
}
```
