### ISSUE TITLE
Oracle stopped on goerli

### ISSUE THREAD

**Issue by uchu** [graphprotocol/block-oracle#235]
https://api.thegraph.com/subgraphs/name/graphprotocol/goerli-epoch-block-oracle

```query MyQuery {
  _meta {
    block {
      number
    }
  }
}
```

Returns block: 8656414 for a while

![image](https://user-images.githubusercontent.com/5249664/225246888-243dba86-2746-44ee-a118-f9975a35b912.png)

**Comment by tilacog** [comment]
Looks like it was a temporary issue. 
Closing this for now.
Thanks for reporting!
