### ISSUE TITLE
mainnet: The Epoch Subgraph is 3 epochs away from the Epoch Manager.

### ISSUE THREAD

**Issue by Pete-LunaNova** [graphprotocol/block-oracle#239]
We are seeing the following error in the agent logs when trying to reallocate:

```The Epoch Subgraph is 3 epochs away from the Epoch Manager. It should never be more than 1 epoch away from the Epoch Manager contract. Please submit an issue at https://github.com/graphprotocol/block-oracle/issues/new```

**Comment by LexPrime** [comment]
Also got this error. Indexer agent can`t close allocation 
``` 
    component: "NetworkMonitor"
    epochManagerCurrentEpoch: 859
    epochSubgraphCurrentEpoch: "856"
    epochDifferenceFromContracts: 3
    networkID: "eip155:100"
[08:00:41.203] WARN (IndexerAgent/1): Epoch subgraph could not be queried
    component: "NetworkMonitor"
    networkID: "eip155:100"
    networkAlias: "gnosis"
    attempt: 4
    retriesLeft: 2
    err: "The Epoch Subgraph is 3 epochs away from the Epoch Manager. It should never be more than 1 epoch away from the Epoch Manager contract. Please submit an issue at https://github.com/graphprotocol/block-oracle/issues/new"```

**Comment by grumas-rc** [comment]
same

[06:24:40.279] ERROR (IndexerAgent/363083): The Epoch Subgraph is 3 epochs away from the Epoch Manager. It should never be more than 1 epoch away from the Epoch Manager contract. Please submit an issue at https://github.com/graphprotocol/block-oracle/issues/new
component: "NetworkMonitor"
epochManagerCurrentEpoch: 859
epochSubgraphCurrentEpoch: "856"
epochDifferenceFromContracts: 3
networkID: "eip155:1"
[06:24:40.279] WARN (IndexerAgent/363083): Epoch subgraph could not be queried
component: "NetworkMonitor"
networkID: "eip155:1"
networkAlias: "mainnet"
attempt: 6
retriesLeft: 0
err: "The Epoch Subgraph is 3 epochs away from the Epoch Manager. It should never be more than 1 epoch away from the Epoch Manager contract. Please submit an issue at https://github.com/graphprotocol/block-oracle/issues/new"

**Comment by tilacog** [comment]
Thanks for reporting!
Closing this as Mainnet Epoch Subgraph has caught up to the chain head.
