### ISSUE TITLE
Monitor if a recent sent message changes the Epoch Subgraph `State` appropriately

### ISSUE THREAD

**Issue by tilacog** [graphprotocol/block-oracle#32]
From a monitoring point of view, it would be interesting if the Block Oracle could validate that a sent message changed the Epoch Subgraph `State` in the expected ways.

If the state doesn't change accordingly, the Block Oracle could emit an alert to the maintainers of all involved components.

**Comment by neysofu** [comment]
@tilacog revisiting this. Should we leave this open? I'm not sure we're still interested in duplicating subgraph logic.

**Comment by tilacog** [comment]
It's not strictly necessary, but maybe we could consider renaming this to:

_**Detect if the state has changed between epochs**_

This could be used as an alarm, given that the subgraph state is expected to change between epochs.

From a code perspective, this would be easy to implement as the Oracle keeps the previous state around, so it would be just diffing the new state against the old one.

wdyt?

**Comment by neysofu** [comment]
I'll add a test for this!

**Comment by neysofu** [comment]
Fixed by https://github.com/graphprotocol/block-oracle/pull/173.
