### ISSUE TITLE
React to a failed Epoch Subgraph 

### ISSUE THREAD

**Issue by tilacog** [graphprotocol/block-oracle#33]
What action does the Block Epoch need to take if the Epoch Subgraps is found in a failed state?

This issue differs from #34.

**Comment by neysofu** [comment]
I'm proposing we go to sleep indefinitely, as I don't think there's anything else we can do. We can close this if you agree.

**Comment by neysofu** [comment]
Fixed by https://github.com/graphprotocol/block-oracle/pull/151.
